version: '3.6'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: tranbo9x

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - mysql
    environment:
      - PDA_ARBITRARY = 1
  statuspage:
    build:
      context: .
    ports:
      - 3000:3000
    links:
      - mysql
    restart: always